module SystemSettings
  HOST_NAME = "http://www.vasdaq.tv/"
  YAML_DB_FORM_ROOT = "#{RAILS_ROOT}/yaml_db_forms"
  APL_LOGGER = Log4r::Logger.get("APLLOG")
  APLERR_LOGGER = Log4r::Logger.get("BTRACE")
end

module ConstUserSettings
  DEFAULT_GOOGLE_API_KEY = "ABQIAAAAAQbQGWHJNPKzo-lgVbQm5hT0xHynmjgBA7h_NPlOmLr3NxUqYhQpN6D71yHzSOrFgpbVPewdpMaAdA"
end


module ConstYamlDbForm
  FILE_SIZE_MIN = 1
  FILE_SIZE_MAX = (50 * 1024)
  FILE_COUNT_MAX = 10
  
  DB_TABLE_MIN = 1
  DB_TABLE_MAX = 64
  DB_COLUMN_MIN = 1
  DB_COLUMN_MAX = 64
  
  MAIL_TO_MAX = 128
  MAIL_TO_MIN = 0
  
  MAIL_SUBJECT_MAX = 128
  MAIL_SUBJECT_MIN = 0
  
  FORM_NAME_MIN = 1
  FORM_NAME_MAX = 64
  FORM_DESC_MIN = 1
  FORM_DESC_MAX = 512
  FORM_BUTTON_MIN = 1
  FORM_BUTTON_MAX = 64
  FORM_ITEMS_MIN = 1
  FORM_ITEMS_MAX = 10
      
  ITEM_NAME_MIN = 1    
  ITEM_NAME_MAX = 64
  ITEM_DESC_MIN = 1
  ITEM_DESC_MAX = 512

  RANGE_COUNT = 2
  RANGE_MIN = -1000
  RANGE_MAX = 1000
  PROHIBIT_MIN = 1
  PROHIBIT_MAX = 10  
  
  TEXT_HIGHT_MIN = 1
  TEXT_HIGHT_MAX = 100
  TEXT_WIDTH_MIN = 1
  TEXT_WIDTH_MAX = 100
  TEXT_LENGTH_MIN = 1
  TEXT_LENGTH_MAX = 100
  TEXT_VALIDATE_MIN = 0
  TEXT_VALIDATE_MAX = 8
  
  RADIO_COUNT_MIN = 2
  RADIO_COUNT_MAX = 10
  RADIO_NAME_MIN = 1
  RADIO_NAME_MAX = 64
  RADIO_VALUE_MIN = 1
  RADIO_VALUE_MAX = 64
  
  LIST_COUNT_MIN = 2
  LIST_COUNT_MAX = 10 
  LIST_NAME_MIN = 1
  LIST_NAME_MAX = 64
  LIST_VALUE_MIN = 1
  LIST_VALUE_MAX = 64

  CHECK_VALUE_MIN = 1
  CHECK_VALUE_MAX = 64

  TEXTAREA_HIGHT_MIN = 1
  TEXTAREA_HIGHT_MAX = 1000
  TEXTAREA_WIDTH_MIN = 1
  TEXTAREA_WIDTH_MAX = 1000
  TEXTAREA_LENGTH_MIN = 1
  TEXTAREA_LENGTH_MAX = 5000
  TEXTAREA_VALIDATE_MIN = 0
  TEXTAREA_VALIDATE_MAX = 8  
end

module Consts
  REFRESH_INTERVAL_MSEC=5*1000*60
end

module Compare
  MORE_THAN = 1
  LESS_THAN = 2
  EQUAL = 0
end
